parsers:
  - name: LegacyCXXParser
    package: '@agoraio-extensions/terra-legacy-cxx-parser'
    args:
      includeHeaderDirs:
        - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.2.3/include'
      parseFiles:
        include:
          - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.2.3/include/*.h'
        exclude:
          - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.2.3/include/AgoraRefPtr.h'
          - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.2.3/include/time_utils.h'
          - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.2.3/include/AgoraOptional.h'
          - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.2.3/include/AgoraRefPtr.h'
          - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.2.3/include/IAgoraH265Transcoder.h'
          - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.2.3/include/IAgoraMediaComponentFactory.h'
          - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.2.3/include/IAgoraParameter.h'
      customHeaders:
        - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.2.3/custom_headers/*.h'
      language: ts
      legacyRenders:
        - TsInterfaceRender
        - TsImplRender

renderers:
  - name: IrisDocRenderer
    package: '@agoraio-extensions/terra_shared_configs'
    args:
      language: ts
      fmtConfig: fmt_ts.yaml
      exportFilePath: ../../src/index.ts
      templateUrl: https://github.com/AgoraIO/agora_doc_source/releases/download/master-build/rn_ng_json_template_en.json
